### ISSUE TITLE
error while buliding

### ISSUE THREAD

**Issue by UTrosh** [sloweax/proxyrot#1]
cc -Wall -Wextra -g proxyrot.c -c -o proxyrot.o
proxyrot.c: In function 'work':
proxyrot.c:408:9: error: a label can only be part of a statement and a declaration is not a statement
  408 |         proxy_info *proxy = get_next_proxy();
      |         ^~~~~~~~~~
make: *** [Makefile:9: proxyrot.o] Error 1

**Comment by sloweax** [comment]
Can you provide the output of `cc -v`?

On `gcc` running `make CC=gcc CFLAGS=-std=gnu11` should build fine

I will be working for it to be compatible with at least `-std=c11` in the meantime

**Comment by JReming85** [comment]
Not sure what was changed, but getting this error when trying to build on Ubuntu 20.04.6 LTS with gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0


```
/opt/proxyrot# make
cc -Wall -Wextra -g -lpthread proxyrot.o util.o socks5.o proxy.o -o proxyrot
/usr/bin/ld: proxyrot.o: in function `main':
/opt/proxyrot/proxyrot.c:153: undefined reference to `pthread_create'
/usr/bin/ld: /opt/proxyrot/proxyrot.c:158: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: proxyrot] Error 1
```

**Comment by sloweax** [comment]
Should be fixed in https://github.com/sloweax/proxyrot/commit/829bb3abd91161d839eb70ffb1357ad203ee545c

Closing due to inactivity
